# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atl < Formula
  desc "AgentTeamLand package manager CLI — install teams, scaffold projects"
  homepage "https://github.com/agentteamland/cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentteamland/cli/releases/download/v0.1.3/atl_0.1.3_darwin_amd64.tar.gz"
      sha256 "b9d962b60351386ab267adb21e42c09a246a4264093e9be12c447f1d61f40079"

      define_method(:install) do
        bin.install "atl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentteamland/cli/releases/download/v0.1.3/atl_0.1.3_darwin_arm64.tar.gz"
      sha256 "0ef5dc6b6c805096e88c0af5566ebb01db1bee7b187b61b6ba542eba26d32576"

      define_method(:install) do
        bin.install "atl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentteamland/cli/releases/download/v0.1.3/atl_0.1.3_linux_amd64.tar.gz"
      sha256 "cb434067f5f1ac61e8b05fa2c74949da0ee23052e70e9ad3f7ff8c44f1facb73"
      define_method(:install) do
        bin.install "atl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentteamland/cli/releases/download/v0.1.3/atl_0.1.3_linux_arm64.tar.gz"
      sha256 "6064e435fbdb195df33bb42a550ddbe4b98b03388820896f75475779768f863d"
      define_method(:install) do
        bin.install "atl"
      end
    end
  end

  test do
    system "#{bin}/atl --version"
  end
end
