# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atl < Formula
  desc "AgentTeamLand package manager CLI — install teams, scaffold projects"
  homepage "https://github.com/agentteamland/cli"
  version "1.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentteamland/cli/releases/download/v1.1.5/atl_1.1.5_darwin_amd64.tar.gz"
      sha256 "0111068f8c4009ebe1613279dd63e33f3ed7914d097ef28b065e64e2331ca565"

      define_method(:install) do
        bin.install "atl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentteamland/cli/releases/download/v1.1.5/atl_1.1.5_darwin_arm64.tar.gz"
      sha256 "2e38d05f3fe1434828df01bd41b7d5abceed34c2788317f66d203a6d77457d2a"

      define_method(:install) do
        bin.install "atl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentteamland/cli/releases/download/v1.1.5/atl_1.1.5_linux_amd64.tar.gz"
      sha256 "d76a33759878972e3d5b876a23f4440ecbaed719f33b39b40efc084f600aef16"
      define_method(:install) do
        bin.install "atl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentteamland/cli/releases/download/v1.1.5/atl_1.1.5_linux_arm64.tar.gz"
      sha256 "d8455412b9b060bca820396af1daf5ca0151e650e95b04ed48d6cae9542b6fd2"
      define_method(:install) do
        bin.install "atl"
      end
    end
  end

  test do
    system "#{bin}/atl --version"
  end
end
